"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # เผื่อใช้กับ path/env

# ---------------------------------------------------------------------
# Base & Security
# ---------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-a7@1g*47#jkrlk1m$t*=%d4x0lx)6we58m-#6py%2o-$6k34c&'
DEBUG = True
ALLOWED_HOSTS = []

# ---------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'products',
    'accounts',
    'dashboard',

    # UI/Dev tools
    'tailwind',
    'theme',
    'django_browser_reload',

    # ↓↓↓ เพิ่มเพื่อ Social Login ด้วย Google ↓↓↓
    'django.contrib.sites',                                 # NEW (จำเป็นสำหรับ allauth)
    'allauth',                                              # NEW
    'allauth.account',                                      # NEW
    'allauth.socialaccount',                                # NEW
    'allauth.socialaccount.providers.google',               # NEW
]

# Tailwind
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ["127.0.0.1"]
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

# ---------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------
# เส้นทางหน้า login/logout/redirect
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'               # เคยประกาศซ้ำไว้ด้านล่าง → รวบมาไว้ที่นี่
LOGOUT_REDIRECT_URL = '/'

SITE_ID = 1                            # NEW (ใช้คู่กับ django.contrib.sites)

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',  # NEW (ของ allauth)
]

# ตั้งค่าสำหรับ allauth (ใช้ email เป็นหลัก ปรับได้)
ACCOUNT_EMAIL_REQUIRED = True          # NEW
ACCOUNT_AUTHENTICATION_METHOD = "email"   # NEW  ("username_email" ก็ได้)
ACCOUNT_EMAIL_VERIFICATION = "optional"   # NEW

# Provider: Google OAuth
SOCIALACCOUNT_PROVIDERS = {            # NEW
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}
SOCIALACCOUNT_LOGIN_ON_GET = True

# ---------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

# ---------------------------------------------------------------------
# URLs / Templates / WSGI
# ---------------------------------------------------------------------
ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # global templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # สำคัญสำหรับ allauth (มีอยู่แล้ว)
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mystorewebit',
        'USER': 'root',
        'PASSWORD': '2547',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = []  # ปิดความซับซ้อนรหัสผ่าน (ปรับตามความเหมาะสม)

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# ---------------------------------------------------------------------
# i18n / Timezone
# ---------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_TZ = False

# ---------------------------------------------------------------------
# Static & Media
# ---------------------------------------------------------------------
STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------
# Session
# ---------------------------------------------------------------------
# หมดอายุเมื่อไร (ตัวอย่างตั้ง 1 วัน = 86400 วินาที)
SESSION_COOKIE_AGE = 86400
SESSION_EXPIRE_AT_BROWSER_CLOSE = False